name: "Fitz: Outfit Rating"
description: "The <b>#1 Outfit rating</b> app. Just Snap & Transform your fashion choice with <b>Fitz</b>."
full_description_title: '<h3>Fitz - Unlock your true fashion potential and receive personalised tips.</h3>'
key_features: '<ul style="font-size: smaller;">
    <li><b>Outfit Rating</b>: Get instant ratings on style, fit, and color coordination</li>
    <li><b>Style Insights</b>: Explore the latest trends and how they fit your personal aesthetic</li>
    <li><b>Fit Guide</b>: Tips on enhancing the fit of your garments for the best look</li>
    <li><b>Color Analysis</b>: Learn which hues suit you best for a vibrant appearance</li>
    <li><b>Fashion Feedback</b>: Receive personalized advice and comments from fashion experts</li>
    <li><b>Trend Alerts</b>: Keep up with the latest in fashion and never miss a beat</li>

</ul>'
full_description_footer: '<h4>Ready to Step Up Your Fashion Game?</h4>

<p><a id="download_button_1" href="https://apps.apple.com/us/app/fitz-outfit-rating/id6477295133?platform=iphone&ppid=cb1a6685-e2b3-45e3-a663-fc910c57664c" target="_blank"><b>Download</b></a> the <a id="download_button_2" href="https://apps.apple.com/us/app/fitz-outfit-rating/id6477295133?platform=iphone&ppid=cb1a6685-e2b3-45e3-a663-fc910c57664c" target="_blank"><b>Fitz app</b></a> and transform your wardrobe today!</p>'

#android: https://telegra.ph/Replace-this-link-07-23
iOS: https://apps.apple.com/us/app/looksmax-ai-umaxx-face-rating/id6477295133?platform=iphone&ppid=cb1a6685-e2b3-45e3-a663-fc910c57664c
#web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
